- id: '1626720070321'
  alias: test_automation
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: efac92f9ea82e46d72160280a8c5a5fe
    entity_id: remote.sony_bravia_tv
    domain: remote
    id: test_trigger_id
  condition: []
  action:
  - service: homeassistant.check_config
  mode: single
- id: '1638656355699'
  alias: Run speedtest
  description: ''
  trigger:
  - platform: time
    at: 09:00
  condition: []
  action:
  - service: speedtestdotnet.speedtest
  mode: single
- id: '1638656723801'
  alias: Report internet speed
  description: Reports internet speed is lower than 100 Mbits
  trigger:
  - platform: numeric_state
    entity_id: sensor.speedtest_download
    below: '100'
  condition: []
  action:
  - service: notify.telegram
    data:
      message: Скорость интернета меньше 100 Мбит!
      target: -373800927
  mode: single
