- id: '1626720070321'
  alias: test_automation
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: efac92f9ea82e46d72160280a8c5a5fe
    entity_id: remote.sony_bravia_tv
    domain: remote
    id: test_trigger_id
  condition: []
  action:
  - service: homeassistant.check_config
  mode: single
- id: '1638656355699'
  alias: Run speedtest
  description: ''
  trigger:
  - platform: time
    at: 09:00
  condition: []
  action:
    - service:  homeassistant.update_entity
      target:
        entity_id:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping
  mode: single
- id: '1638656723801'
  alias: Report internet speed
  description: Reports internet speed is lower than 100 Mbits
  trigger:
  - platform: numeric_state
    entity_id: sensor.speedtest_download
    below: '100'
  condition: []
  action:
  - service: notify.telegram
    data:
      message: Скорость интернета меньше 100 Мбит!
      target: -373800927
  mode: single
- id: '1645039793424'
  alias: bedroom_light_mirror_warm
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 221279b40255919278489d25e61e1cae
    type: action
    subtype: on_right
    discovery_id: 0x00047400008bac47 action_on_right
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: light.bedroom_light_mirror_all
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: light.bedroom_light_mirror_all
        attribute: brightness
        state: '12'
    - condition: not
      conditions:
      - condition: state
        entity_id: light.bedroom_light_mirror_all
        attribute: color_temp
        state: '313'
  action:
  - scene: scene.bedroom_light_mirror_warm
  mode: single
- id: '1645040237071'
  alias: bedroom_light_mirror_off
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 221279b40255919278489d25e61e1cae
    type: action
    subtype: 'off'
    discovery_id: 0x00047400008bac47 action_off
  condition:
  - condition: device
    type: is_on
    device_id: 508a7a13f1c38051cc0d27ac18668706
    entity_id: light.bedroom_light_mirror_all
    domain: light
  action:
  - type: turn_off
    device_id: 508a7a13f1c38051cc0d27ac18668706
    entity_id: light.bedroom_light_mirror_all
    domain: light
  mode: single
- id: '1645040588037'
  alias: bedroom_light_mirror_max
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 221279b40255919278489d25e61e1cae
    type: action
    subtype: on_right
    discovery_id: 0x00047400008bac47 action_on_right
  condition:
  - condition: numeric_state
    entity_id: light.bedroom_light_mirror_all
    attribute: brightness
    below: '100'
  - condition: numeric_state
    entity_id: light.bedroom_light_mirror_all
    attribute: color_temp
    above: '250'
  action:
  - scene: scene.bedroom_light_mirror_max
  mode: single
