# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


homeassistant:
  name: Kitty's home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 130
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include includes/customize.yaml
  packages: !include_dir_merge_named includes/packages

# Text to speech
tts:
  - platform: google_translate

http:
  trusted_proxies: 
    - 127.0.0.1
  server_port: 8123
  use_x_forwarded_for: true

mqtt:
  broker: core-mosquitto
  discovery: true
  discovery_prefix: homeassistant
  username: mqtt
  password: !secret mqtt
  
lovelace:
  mode: yaml

apcupsd:
  host: a722577e-apcupsd
  port: 3551
  
telegram_bot:
  - platform: polling
    api_key: !secret bot_main
    allowed_chat_ids:
      - -332716958 # tech
      - -373800927 # main
      - 42389353 # me
notify:
  - platform: telegram
    name: telegram
    chat_id: -373800927 
  - platform: telegram
    name: telegram_tech
    chat_id: -332716958

# ext files
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
group: !include includes/groups.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml

# ext dirs
sensor: !include_dir_merge_list includes/sensor
automation: !include_dir_merge_list includes/automation
