# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


homeassistant:
  name: Kitty's home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 130
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include includes/customize.yaml
  packages: !include_dir_merge_named includes/packages
  legacy_templates: false

# Text to speech
tts:
  - platform: google_translate

http:
  trusted_proxies: 
    - 127.0.0.1
  server_port: 8123
  use_x_forwarded_for: true

mqtt:
  broker: core-mosquitto
  discovery: true
  discovery_prefix: homeassistant
  username: mqtt
  password: !secret mqtt
  
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
      type: module

apcupsd:
  host: a722577e-apcupsd
  port: 3551

weather:
  - platform: yandex_weather
    api_key: !secret yandex_api_key
    scan_interval: 3600

telegram_bot:
  - platform: polling
    api_key: !secret bot_main
    allowed_chat_ids:
      - -332716958 # tech
      - -373800927 # main
      - 42389353 # me
      - 182901558 # Natasha
      
#telegram_mybot:
#  - platform: polling
#    api_key: !secret bot_tech
#    allowed_chat_ids:
#      - -332716958 # tech
#      - -373800927 # main
#      - 42389353 # me
#      - 182901558 # Natasha
      
notify:
  - platform: telegram
    name: telegram
    chat_id: -373800927 
  - platform: telegram
    name: telegram_tech
    chat_id: -332716958
    
#zabbix:
#  host: 'zabbix.goes.black'
#  #port: 443
#  path: ''
#  ssl: true
#  username: homeassistant
#  password: !secret zabbix
#  publish_states_host: homeassistant
#  exclude:
#    domains:
#      - device_tracker
#    entities:
#      - sun.sun
#      - sensor.time
      
# https://github.com/bessarabov/bessarabov_custom_component
bessarabov:
  token: !secret bessarabov_token

# ext files
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_text: !include includes/input_text.yaml
group: !include includes/groups.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
deebot: !include includes/deebot.yaml
recorder: !include includes/recorder.yaml
google_assistant: !include includes/google.yaml

# ext dirs
sensor: !include_dir_merge_list includes/sensor
automation: !include_dir_merge_list includes/automation
camera: !include_dir_merge_list includes/cameras
light: !include_dir_merge_list includes/light
