# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


homeassistant:
  name: Kitty's home
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  elevation: 130
  unit_system: metric
  time_zone: Europe/Moscow
  customize: !include includes/customize.yaml
  packages: !include_dir_merge_named includes/packages
  country: RU

# Text to speech
tts:
  - platform: google_translate

http:
  trusted_proxies: 
    - 127.0.0.1
  server_port: 8123
  use_x_forwarded_for: true

api:

mqtt:
  sensor: !include includes/mqtt_sensor.yaml
  
lovelace:
  resources:
    - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
      type: module

#weather:
#  - platform: yandex_weather
#    api_key: !secret yandex_api_key
#    scan_interval: 3600

telegram_bot:
  - platform: polling
    api_key: !secret bot_main
    allowed_chat_ids:
      - -332716958 # tech
      - -373800927 # main
      - 42389353 # me
      - 182901558 # Natasha
      
#telegram_mybot:
#  - platform: polling
#    api_key: !secret bot_tech
#    allowed_chat_ids:
#      - -332716958 # tech
#      - -373800927 # main
#      - 42389353 # me
#      - 182901558 # Natasha
      
notify:
  - platform: telegram
    name: telegram
    chat_id: -373800927 
  - platform: telegram
    name: telegram_tech
    chat_id: -332716958
    
#zabbix:
#  host: 'zabbix.goes.black'
#  #port: 443
#  path: ''
#  ssl: true
#  username: homeassistant
#  password: !secret zabbix
#  publish_states_host: homeassistant
#  exclude:
#    domains:
#      - device_tracker
#    entities:
#      - sun.sun
#      - sensor.time
      
# https://github.com/bessarabov/bessarabov_custom_component
bessarabov:
  token: !secret bessarabov_token

lkcomu_interrao:

  # Тип выбранного ЛК
  # Значение по умолчанию: moscow
  # Перечень возможных значений:
  # - altai (ЛК Алтай (АО «АлтайЭнергосбыт»))
  # - bashkortostan (ЛКК ЭСКБ (Башэлектросбыт))
  # - moscow (ЕЛК ЖКХ (АО «Мосэнергосбыт», МосОблЕИРЦ, ПАО «Россети Московский регион»))
  # - oryol (ЛКК Орел (ООО «Орловский энергосбыт»))
  # - saratov (ЛК Саратов (ПАО «Саратовэнерго»))
  # - sevesk (ЕЛК Вологда (Северная сбытовая компания))
  # - tambov (ЛК ТЭСК (Тамбовская энергосбытовая компания))
  # - tomsk (ЕЛК Томск (Томскэнергосбыт / Томск РТС))
  # - volga (ЛКК ЭСВ (Энергосбыт Волга))
  type: moscow

  # Имя пользователя
  # Обязательный параметр
  username: "..."

  # Пароль
  # Обязательный параметр
  password: "..."

  # Конфигурация по умолчанию для лицевых счетов
  # Необязательный параметр
  #  # Данная конфигурация применяется, если отсутствует  # конкретизация, указанная в разделе `accounts`.
  default:

    # Получать ли ссылки на логотипы
    # Значение по умолчанию: истина (true)
    logos: true

    # Добавлять ли объект(-ы): Информация о лицевом счёте
    # Значение по умолчанию: истина (true)
    accounts: true

    # Добавлять ли объект(-ы): Счётчик коммунальных услуг
    # Значение по умолчанию: истина (true)
    meters: true

    # Добавлять ли объект(-ы): Последний зарегистрированный платёж
    # Значение по умолчанию: истина (true)
    last_payment: true

    # Добавлять ли объект(-ы): Последняя выпущенная квитанция
    # Значение по умолчанию: истина (true)
    last_invoice: true

  # Настройки для отдельных лицевых счетов
  # Необязательный параметр
  #accounts:
  
# ext files
timer: !include includes/timer.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
input_text: !include includes/input_text.yaml
input_select: !include includes/input_select.yaml
group: !include includes/groups.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
#deebot: !include includes/deebot.yaml
recorder: !include includes/recorder.yaml
google_assistant: !include includes/google.yaml

# ext dirs
sensor: !include_dir_merge_list includes/sensor
automation: !include_dir_merge_list includes/automation
camera: !include_dir_merge_list includes/cameras
light: !include_dir_merge_list includes/light
binary_sensor: !include_dir_merge_list includes/binary_sensor
command_line: !include_dir_merge_list includes/command_line
frontend:
  themes: !include_dir_merge_named themes
