substitutions:
  devicename: bedroom_light_mirror
  switch_name: bedroom_light_mirror
  
esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  #ap:
  #  ssid: "Bedroom Light Mirror"
  #  password: "OOvueGqzpoHC"

#captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: secret! espapi

ota:
  password: secret! espapi
  
status_led:
  pin:
    number: GPIO13
    inverted: true

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - light.toggle: 
          id: $devicename

  - platform: gpio
    name: "$devicename switch"
    pin: GPIO04
    id: switch_1
    on_press:
      then:
        - light.turn_on:
            id: $devicename
    on_release:
      then:
        - light.turn_off:
            id: $devicename

# switch:
#   - platform: gpio
#     name: "$devicename relay"
#     icon: "mdi:lightbulb_outline"
#     pin: GPIO12
#     id: relay_1
#     restore_mode: restore_default_off
    
output:
  - platform: gpio
    id: light_relay
    pin: GPIO12
    
light:
  - platform: binary
    id: $devicename
    name: $switch_name
    output: light_relay
  